# version: '3.8'

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: kai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-kai}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kai-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: kai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
    networks:
      - kai-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: kai_keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresdb:5432/${KEYCLOAK_DB:-keycloak}
      - KC_DB_USERNAME=${POSTGRES_USER:-postgres}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - KC_HOSTNAME=substanceai.cloud
      - KC_HOSTNAME_PATH=/auth
#      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY=edge
#      - KC_HOSTNAME_URL=https://substanceai.cloud/auth
#      - KC_HOSTNAME_STRICT_HTTPS=true
    volumes:
      - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - kai-network

  backend:
    build: ./backend
    container_name: kai_backend
    env_file:
      - ./backend/.env
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - DB_HOST=${DB_HOST:-postgresdb}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=${POSTGRES_DB:-kai}
      - DB_PORT=${DB_PORT:-5432}
      - PORT=${PORT:-5000}
      - FRONTEND_URL=https://substanceai.cloud
      - BACKEND_URL=https://substanceai.cloud/api
      - KEYCLOAK_URL=https://substanceai.cloud/auth
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-kai}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgresdb
    networks:
      - kai-network

  frontend:
    build: ./frontend
    container_name: kai_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=/api
      - VITE_KEYCLOAK_URL=https://substanceai.cloud/auth
      - VITE_KEYCLOAK_REALM=${KEYCLOAK_REALM:-kai}
      - VITE_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-kai-frontend}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - kai-network

volumes:
  postgres_data:
  uploads_data:

networks:
  kai-network:
    driver: bridge
