name: Build and Deploy Containers

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: stitchflowacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

          # ---------------- BACKEND ----------------
      - name: Deploy Backend (Container App)
        run: |
          az containerapp update \
            --name kaibysobana-backend \
            --resource-group Deep_PerPro \
            --image stitchflowacr.azurecr.io/stitchflow-backend:latest

      # ---------------- FRONTEND ----------------
      - name: Deploy Frontend (Container App)
        run: |
          az containerapp update \
            --name kaibysobana-frontend \
            --resource-group Deep_PerPro \
            --image stitchflowacr.azurecr.io/stitchflow-frontend:latest

      # ---------------- KEYCLOAK ----------------
      - name: Deploy Keycloak (Container App)
        run: |
          az containerapp update \
            --name kaibysobana-keycloak \
            --resource-group Deep_PerPro \
            --image stitchflowacr.azurecr.io/stitchflow-keycloak:latest